import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import CursorOne from "./components/cursorOne";
import CursorTwo from "./components/cursorTwo";
import CursorThree from "./components/cursorThree";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {children}
      </body>
    </html>
  );
}
